language: php
php:
- 5.6
env:
  global:
    - SELENIUM_SERVER="hub.browserstack.com"
    - SCREENSHOTS_PATH=""
    - APP_HOST="fatturatutto.it"
  matrix:
    # Test should be runned in sequence and not in parallel because there are some security checks (about sessions management) on the login feature of the webapp
    # see: https://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting/
    - BROWSER="chrome"
    - BROWSER="firefox"
    - BROWSER="safari"
before_script:
  - php ./script/before_script.php
  # - composer self-update
  - composer install --prefer-source --no-interaction --dev
  #
  # BrowserStack (da riportare su script bash, vedi https://github.com/travis-ci/travis-ci/issues/879)
  - wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  - unzip BrowserStackLocal-linux-x64.zip
  - ./BrowserStackLocal $BROWSERSTACK_ACCESS_KEY localhost,8001,0 > /dev/null &
  - sleep 10
  
script: phpunit
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
    on_success: change # default: change
    on_failure: always # default: always
  webhooks: 
    urls:
      - http://95.224.129.129:81/notification?secret=${IUBAR_WH_TOKEN}
      - https://webhooks.gitter.im/e/${GITTER_IM_TOKEN}
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    

