language: php
php:
- 5.5
env:
  global:
    - SERVER="http://ondemand.saucelabs.com:80"
    - SCREENSHOTS_PATH=""
  matrix:
    - BROWSER="chrome"
    - BROWSER="marionette"
    - BROWSER="phantomjs"
before_script:
  # - composer self-update
  - cd tests
  - composer install --prefer-source --no-interaction --dev
script: phpunit
notifications:
  email:
    recipients:
      - borgogelli@iubar.it
    on_success: change # default: change
    on_failure: always # default: always

