language: php
php:
- 5.5
- 5.6
before_script:
  - composer self-update
  - cd tests
  - composer install --prefer-source --no-interaction --dev
script: phpunit
notifications:
  email:
    recipients:
      - borgogelli@iubar.it
    on_success: change # default: change
    on_failure: always # default: always

