language: php
php:
- 5.5
env:
- BROWSER="chrome"
- SERVER="http://ondemand.saucelabs.com:80"
- SCREENSHOTS_PATH=""

  global:
    - CAMPFIRE_TOKEN=abc123
    - TIMEOUT=1000
  matrix:
    - USE_NETWORK=true
      - USE_NETWORK=false
before_script:
  # - composer self-update
  - cd tests
  - composer install --prefer-source --no-interaction --dev
script: phpunit --configuration ./tests/script/phpunit_chrome_saucelabs.xml
notifications:
  email:
    recipients:
      - borgogelli@iubar.it
    on_success: change # default: change
    on_failure: always # default: always

