language: php
php:
- 5.5
env:
  global:
    - SERVER="ondemand.saucelabs.com"
    - SCREENSHOTS_PATH=""
  matrix:
    - BROWSER="chrome"
    - BROWSER="marionette"
    #- BROWSER="phantomjs"
before_script:
  # - composer self-update
  - cd tests
  - composer install --prefer-source --no-interaction --dev
  - cd ..
  # Use xvfb 
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  #- sleep 3 # give xvfb some time to start  
script: phpunit
addons:
  sauce_connect: true
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
    on_success: change # default: change
    on_failure: always # default: always
  webhooks: http://95.224.129.129:81/notification?secret=${WH_TOKEN}

