language: php
php:
- 5.5
env:
  global:
    - SELENIUM_SERVER="ondemand.saucelabs.com"
    # - SELENIUM_SERVER="localhost:4444"
    - SCREENSHOTS_PATH=""
  matrix:
    - BROWSER="chrome"
    - BROWSER="firefox"
    #- BROWSER="phantomjs"
before_script:
  # - composer self-update
  - cd tests
  - composer install --prefer-source --no-interaction --dev
  - cd ..
  # Download and run Selenium (+ https://github.com/jarib/selenium-travis)
  # - "wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar"
  # - "java -jar selenium-server-standalone-2.43.1.jar > /dev/null &"  
  # Use xvfb 
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  #- sleep 3 # give xvfb some time to start 
script: phpunit
addons:
  sauce_connect: true
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
    on_success: change # default: change
    on_failure: always # default: always
  webhooks: 
    urls:
      - http://95.224.129.129:81/notification?secret=${IUBAR_WH_TOKEN}
      - https://webhooks.gitter.im/e/${GITTER_IM_TOKEN}
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    

