language: php
php:
  - 7.2
env:
  global:
    - SELENIUM_SERVER="localhost"
    - SCREENSHOTS_PATH=""
    - APP_HOST="fatturatutto.it"
  matrix:
    # Test should be runned in sequence and not in parallel because there are some security checks (about sessions management) on the login feature of the webapp
    # see: https://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting/
    - BROWSER="chrome"
    - BROWSER="firefox"
    - BROWSER="safari"
    #- BROWSER="phantomjs"
before_script:
  - php ./script/before_script.php
  # - composer self-update
  - composer require --dev jakub-onderka/php-parallel-lint
  - composer require --dev jakub-onderka/php-console-highlighter
  - composer install --prefer-source --no-suggest --no-progress --no-interaction 
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/phpstan -V
  - vendor/bin/phpstan analyse src --no-interaction --no-progress --level 0
  #
  #
  # Download and run Selenium (+ https://github.com/jarib/selenium-travis)
  - "wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar"
  - "java -jar selenium-server-standalone-2.43.1.jar > /dev/null &" 
  # DUBBIO: e chrome ? e il driver di selenoum per chrome ?
  # Ho l'impressione che questo script non funzioni
  # Use xvfb 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start     
script: phpunit
notifications:
  email:
    recipients:
      - ${EMAIL_BORGO}
    on_success: change # default: change
    on_failure: always # default: always
  webhooks: 
    urls:
      - http://217.133.38.27:81/notification?secret=${IUBAR_WH_TOKEN}
      - https://webhooks.gitter.im/e/${GITTER_IM_TOKEN}
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    

